### PR TITLE
Added support for specific lines at a stop by adding '/<line-name>' t…

### PR DESCRIPTION
**Pull request by TheConfusedCat**
…o the stop specification

### CODE REVIEW

**Comment by tofuSCHNITZEL** [comment]
this is already possible in the "beta" version:
https://github.com/tofuSCHNITZEL/home-assistant-wienerlinien/tree/dev

https://github.com/tofuSCHNITZEL/home-assistant-wienerlinien/releases/tag/1.3.0-beta

**Comment by TheConfusedCat** [comment]
Ah, perfect. I was not aware. Do you know when you're going to publish it? I could figure out how to add the dev branch as a custom repository to HACS (reports that the repository is already included in HACS).
It seems to work anyway quite fine.
Thanks!

**Comment by tofuSCHNITZEL** [comment]
It will probably not be "released" because there are still multiple issues with this whole thing that probably only get solved by rewriting everything from the ground up. (with config flow etc)
you can get the beta version via hacs although I cant find where to enable / switch to beta version. so probably just download the zip from the dev branch and manually add it to "custom_components"

**Comment by TheConfusedCat** [comment]
Ok, understood. Thank you!

**Pull request closed without merging**
